.TH HSH 1 "April 2024" "0.01" "hsh man page"
.SH NAME
.B hsh
\- Holberton SHell
.SH SYNOPSIS
.B hsh
[No options yet]
.SH DESCRIPTION
.B hsh
is a simple interactive command interpreter. It executes commands read from the standard input. hsh is not fully featured yet. It can only handle simple commands in the form: "<command> [options]"
.SH BUILTIN COMMANDS
.TP
.B ls
Print the list of files in the current directory.
.TP
.B env
Print the environment variables.
.TP
.B exit
Exit the shell gracefully.
.SH AUTHORS
Charlène SCOMPARIN
.br
Antonin NOYELLE
